# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Tim Knight
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A blog about Ruby, Ruby on Rails, JavaScript and my journey learning web development." # used by search engines

  # Header and footer text
  footer_text: >
  # Icons
  rss: false
  email_address: hey@timmilesknight.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "timmknight"
  google_plus:
  instagram:
  linkedin:  http://www.linkedin.com/profile/view?id=346711298
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  twitter: "timmilesknight"
  wordpress: 
  youtube:

  # Scripts
  google_analytics: "UA-63850501-1"
  #disqus_shortname: tknightuk
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:400,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
